### ISSUE TITLE
If the initialState argument of createReducer is nil, then its actionHandlers are never called.

### ISSUE THREAD

**Issue by Mduro** [Roblox/rodux#39]
Consider the following code:

```lua
local Rodux = require(workspace.Rodux)

local testReducer = Rodux.createReducer(
	nil,
	{
		TestStringSet = function(state, action)
			print("TestStringSet was called")
			return action.string
		end
	}
)

local reducer = Rodux.combineReducers(
	{
		testString = testReducer
	}
)

local SetTestString = function(str)
	return {
		type = "TestStringSet",
		string = str
	}
end

local store = Rodux.Store.new(reducer)

store:dispatch(SetTestString("foo"))
print(store:getState().testString)
```

When I run this, only `nil` is printed. `TestStringSet was called` also wasn't printed, which means that the handler wasn't called.

When I change the initialState argument of `createReducer` from `nil` to any non-nil value (`{}` for example"), `TestStringSet was called` and `foo` are printed, in that order.

**Comment by LPGhatguy** [comment]
I stared at this for awhile, since it didn't make sense to me why this would happen!

This was fixed in #33, which probably wasn't in the last binary release for Rodux. You should be able to pull in the latest Git master via Rojo, but I'll go ahead and publish a new release as well.

**Comment by Mduro** [comment]
The .rbxm release you made very recently still contains the lines 
```
if state == nil then
	return initialState
end
```

In createReducer, so the bug still persists. Just a heads up (unless this wasn't included because it was a breaking change).

**Comment by Mduro** [comment]
Right, my bad. Should have occurred to me to test on the latest version of the code. Thanks for the new release!
